---
name: bq27427
description: Driver for the BQ27427 1-Cell Fuel Gauge
version: 0.1.0
groups:
  - battery
  - current
code_owners:
  - sjuliancarrizo
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp32c2
  - esp32c3
  - esp32c5
  - esp32c6
  - esp32c61
  - esp32h2
  - esp32p4
  - esp32s2
  - esp32s3
  - esp8266
license: MIT
copyrights:
  - name: sjuliancarrizo
    year: 2025
