---
name: Build examples
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  build-examples:
    uses: esp-idf-lib/shared-workflows/.github/workflows/build-examples.yml@main
